import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar is generated from the docs/ folder structure (see _category_.json
// files there for section labels and ordering).
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
